### ISSUE TITLE
can not work on ubuntu22.04 

### ISSUE THREAD

**Issue by mostcute** [ErrorNoInternet/mkfs.ext2#1]
```
root@disk:~# ./gomk -device /dev/sdb
error: seek /dev/sdb: invalid argument
```

**Comment by mostcute** [comment]
the deviceInformation.Size() == 0

**Comment by ErrorNoInternet** [comment]
Something else seems to be broken (IO error), but it isn't related to this. Investigating...

**Comment by ErrorNoInternet** [comment]
Fixed, apparently something changed around 6.7-rc1 (which I am running right now).
![image](https://github.com/ErrorNoInternet/mkfs.ext2/assets/61157623/66e33cc0-90c4-427a-9bd9-f594eb7fa366)

**Comment by mostcute** [comment]
So is it still compatible with old kernels?

**Comment by ErrorNoInternet** [comment]
I believe so yes, older kernels ignored that bug, but newer kernels aren't happy with it.
